{"cells":[{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":3808,"status":"ok","timestamp":1708057688624,"user":{"displayName":"ajay chanumolu","userId":"14872455574354088069"},"user_tz":-330},"id":"ddyQ8HE8zeYj","outputId":"a90adcce-8c3c-4339-bab9-4745c6209baf"},"outputs":[{"name":"stdout","output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"]}],"source":["#before running this please change the RUNTIME to GPU (Runtime -> Change runtime type -> set harware accelarotor as GPU)\n","#Mount our google drive\n","from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","execution_count":5,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":462},"executionInfo":{"elapsed":29557,"status":"error","timestamp":1708057766919,"user":{"displayName":"ajay chanumolu","userId":"14872455574354088069"},"user_tz":-330},"id":"3vj15Vde0Gxs","outputId":"cfb72b61-5e60-40b0-ef44-b78f8830e0e8"},"outputs":[{"name":"stdout","output_type":"stream","text":["Requirement already satisfied: face_recognition in /usr/local/lib/python3.10/dist-packages (1.3.0)\n","Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from face_recognition) (0.3.0)\n","Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.10/dist-packages (from face_recognition) (8.1.7)\n","Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.10/dist-packages (from face_recognition) (19.24.2)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from face_recognition) (1.25.2)\n","Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from face_recognition) (9.4.0)\n"]},{"ename":"RuntimeError","evalue":"Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-install-hstm1859/dlib_20ec00742d6b41d0af1fdd8685ac27cd/dlib/cuda/gpu_data.cpp:204. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)","\u001b[0;32m<ipython-input-5-2ee32e2f8092>\u001b[0m in \u001b[0;36m<cell line: 12>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mcv2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     11\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmatplotlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpyplot\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 12\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mface_recognition\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/face_recognition/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0m__version__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'1.2.3'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mapi\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mload_image_file\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_locations\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbatch_face_locations\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_landmarks\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_encodings\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcompare_faces\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_distance\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/face_recognition/api.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     25\u001b[0m \u001b[0mcnn_face_detection_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mface_recognition_models\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcnn_face_detector_model_location\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 26\u001b[0;31m \u001b[0mcnn_face_detector\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcnn_face_detection_model_v1\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcnn_face_detection_model\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     27\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     28\u001b[0m \u001b[0mface_recognition_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mface_recognition_models\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mface_recognition_model_location\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mRuntimeError\u001b[0m: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-install-hstm1859/dlib_20ec00742d6b41d0af1fdd8685ac27cd/dlib/cuda/gpu_data.cpp:204. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version"]}],"source":["#import libraries\n","!pip3 install face_recognition\n","import torch\n","import torchvision\n","from torchvision import transforms\n","from torch.utils.data import DataLoader\n","from torch.utils.data.dataset import Dataset\n","import os\n","import numpy as np\n","import cv2\n","import matplotlib.pyplot as plt\n","import face_recognition"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":394,"status":"ok","timestamp":1707971249095,"user":{"displayName":"ajay chanumolu","userId":"14872455574354088069"},"user_tz":-330},"id":"5pOAwiWIBPR-","outputId":"e67b95e2-86ba-4b3d-bf93-a5ddf7d9c991"},"outputs":[{"name":"stdout","output_type":"stream","text":["nvcc: NVIDIA (R) Cuda compiler driver\n","Copyright (c) 2005-2023 NVIDIA Corporation\n","Built on Tue_Aug_15_22:02:13_PDT_2023\n","Cuda compilation tools, release 12.2, V12.2.140\n","Build cuda_12.2.r12.2/compiler.33191640_0\n"]}],"source":["!nvcc --version"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":4615,"status":"ok","timestamp":1707971259200,"user":{"displayName":"ajay chanumolu","userId":"14872455574354088069"},"user_tz":-330},"id":"-YI44rSwBRDJ","outputId":"f41b3ecb-5632-4fc8-a974-cc76744f73f8"},"outputs":[{"name":"stdout","output_type":"stream","text":["Requirement already satisfied: face_recognition in /usr/local/lib/python3.10/dist-packages (1.3.0)\n","Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from face_recognition) (0.3.0)\n","Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.10/dist-packages (from face_recognition) (8.1.7)\n","Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.10/dist-packages (from face_recognition) (19.24.2)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from face_recognition) (1.25.2)\n","Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from face_recognition) (9.4.0)\n"]}],"source":["!pip3 install --upgrade face_recognition"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":335},"executionInfo":{"elapsed":997,"status":"error","timestamp":1707971263036,"user":{"displayName":"ajay chanumolu","userId":"14872455574354088069"},"user_tz":-330},"id":"w6WzWzFlBSt6","outputId":"16266b67-c27f-4c48-a3b7-ac373c885a29"},"outputs":[{"ename":"RuntimeError","evalue":"Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-install-lut4y97d/dlib_c4530f2ad90f44009d2698b667c210bb/dlib/cuda/gpu_data.cpp:204. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)","\u001b[0;32m<ipython-input-7-ca17cc6b8bdb>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mface_recognition\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/face_recognition/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0m__version__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'1.2.3'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mapi\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mload_image_file\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_locations\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbatch_face_locations\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_landmarks\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_encodings\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcompare_faces\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_distance\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/face_recognition/api.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     25\u001b[0m \u001b[0mcnn_face_detection_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mface_recognition_models\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcnn_face_detector_model_location\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 26\u001b[0;31m \u001b[0mcnn_face_detector\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcnn_face_detection_model_v1\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcnn_face_detection_model\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     27\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     28\u001b[0m \u001b[0mface_recognition_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mface_recognition_models\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mface_recognition_model_location\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mRuntimeError\u001b[0m: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-install-lut4y97d/dlib_c4530f2ad90f44009d2698b667c210bb/dlib/cuda/gpu_data.cpp:204. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version"]}],"source":["import face_recognition"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"C3r-9rMc1DmO"},"outputs":[],"source":["#import libraries\n","import torch\n","from torch.autograd import Variable\n","import time\n","import os\n","import sys\n","import os\n","from torch import nn\n","from torchvision import models"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"g1G0IoVy2Pc7"},"outputs":[],"source":["#Model with feature visualization\n","from torch import nn\n","from torchvision import models\n","class Model(nn.Module):\n","    def __init__(self, num_classes,latent_dim= 2048, lstm_layers=1 , hidden_dim = 2048, bidirectional = False):\n","        super(Model, self).__init__()\n","        model = models.resnext50_32x4d(pretrained = True)\n","        self.model = nn.Sequential(*list(model.children())[:-2])\n","        self.lstm = nn.LSTM(latent_dim,hidden_dim, lstm_layers,  bidirectional)\n","        self.relu = nn.LeakyReLU()\n","        self.dp = nn.Dropout(0.4)\n","        self.linear1 = nn.Linear(2048,num_classes)\n","        self.avgpool = nn.AdaptiveAvgPool2d(1)\n","    def forward(self, x):\n","        batch_size,seq_length, c, h, w = x.shape\n","        x = x.view(batch_size * seq_length, c, h, w)\n","        fmap = self.model(x)\n","        x = self.avgpool(fmap)\n","        x = x.view(batch_size,seq_length,2048)\n","        x_lstm,_ = self.lstm(x,None)\n","        return fmap,self.dp(self.linear1(x_lstm[:,-1,:]))"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"avpp16KLze7T"},"outputs":[],"source":["im_size = 112\n","mean=[0.485, 0.456, 0.406]\n","std=[0.229, 0.224, 0.225]\n","sm = nn.Softmax()\n","inv_normalize =  transforms.Normalize(mean=-1*np.divide(mean,std),std=np.divide([1,1,1],std))\n","def im_convert(tensor):\n","    \"\"\" Display a tensor as an image. \"\"\"\n","    image = tensor.to(\"cpu\").clone().detach()\n","    image = image.squeeze()\n","    image = inv_normalize(image)\n","    image = image.numpy()\n","    image = image.transpose(1,2,0)\n","    image = image.clip(0, 1)\n","    cv2.imwrite('./2.png',image*255)\n","    return image\n","\n","def predict(model,img,path = './'):\n","  fmap,logits = model(img.to('cuda'))\n","  params = list(model.parameters())\n","  weight_softmax = model.linear1.weight.detach().cpu().numpy()\n","  logits = sm(logits)\n","  _,prediction = torch.max(logits,1)\n","  confidence = logits[:,int(prediction.item())].item()*100\n","  print('confidence of prediction:',logits[:,int(prediction.item())].item()*100)\n","  idx = np.argmax(logits.detach().cpu().numpy())\n","  bz, nc, h, w = fmap.shape\n","  out = np.dot(fmap[-1].detach().cpu().numpy().reshape((nc, h*w)).T,weight_softmax[idx,:].T)\n","  predict = out.reshape(h,w)\n","  predict = predict - np.min(predict)\n","  predict_img = predict / np.max(predict)\n","  predict_img = np.uint8(255*predict_img)\n","  out = cv2.resize(predict_img, (im_size,im_size))\n","  heatmap = cv2.applyColorMap(out, cv2.COLORMAP_JET)\n","  img = im_convert(img[:,-1,:,:,:])\n","  result = heatmap * 0.5 + img*0.8*255\n","  cv2.imwrite('/content/1.png',result)\n","  result1 = heatmap * 0.5/255 + img*0.8\n","  r,g,b = cv2.split(result1)\n","  result1 = cv2.merge((r,g,b))\n","  plt.imshow(result1)\n","  plt.show()\n","  return [int(prediction.item()),confidence]\n","#img = train_data[100][0].unsqueeze(0)\n","#predict(model,img)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"asSbpP8fzlFj"},"outputs":[],"source":["#!pip3 install face_recognition\n","import torch\n","import torchvision\n","from torchvision import transforms\n","from torch.utils.data import DataLoader\n","from torch.utils.data.dataset import Dataset\n","import os\n","import numpy as np\n","import cv2\n","import matplotlib.pyplot as plt\n","import face_recognition\n","class validation_dataset(Dataset):\n","    def __init__(self,video_names,sequence_length = 60,transform = None):\n","        self.video_names = video_names\n","        self.transform = transform\n","        self.count = sequence_length\n","    def __len__(self):\n","        return len(self.video_names)\n","    def __getitem__(self,idx):\n","        video_path = self.video_names[idx]\n","        frames = []\n","        a = int(100/self.count)\n","        first_frame = np.random.randint(0,a)\n","        for i,frame in enumerate(self.frame_extract(video_path)):\n","            #if(i % a == first_frame):\n","            faces = face_recognition.face_locations(frame)\n","            try:\n","              top,right,bottom,left = faces[0]\n","              frame = frame[top:bottom,left:right,:]\n","            except:\n","              pass\n","            frames.append(self.transform(frame))\n","            if(len(frames) == self.count):\n","              break\n","        #print(\"no of frames\",len(frames))\n","        frames = torch.stack(frames)\n","        frames = frames[:self.count]\n","        return frames.unsqueeze(0)\n","    def frame_extract(self,path):\n","      vidObj = cv2.VideoCapture(path)\n","      success = 1\n","      while success:\n","          success, image = vidObj.read()\n","          if success:\n","              yield image\n","def im_plot(tensor):\n","    image = tensor.cpu().numpy().transpose(1,2,0)\n","    b,g,r = cv2.split(image)\n","    image = cv2.merge((r,g,b))\n","    image = image*[0.22803, 0.22145, 0.216989] +  [0.43216, 0.394666, 0.37645]\n","    image = image*255.0\n","    plt.imshow(image.astype(int))\n","    plt.show()"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":219},"executionInfo":{"elapsed":10,"status":"error","timestamp":1708054534940,"user":{"displayName":"ajay chanumolu","userId":"14872455574354088069"},"user_tz":-330},"id":"J8YkC-vwzrkE","outputId":"5a911582-80b7-49f9-e92e-04c491dc77b1"},"outputs":[{"ename":"NameError","evalue":"name 'transforms' is not defined","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-f36efca4a359>\u001b[0m in \u001b[0;36m<cell line: 6>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mstd\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0.229\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0.224\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0.225\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m train_transforms = transforms.Compose([\n\u001b[0m\u001b[1;32m      7\u001b[0m                                         \u001b[0mtransforms\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mToPILImage\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m                                         \u001b[0mtransforms\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mResize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mim_size\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mim_size\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mNameError\u001b[0m: name 'transforms' is not defined"]}],"source":["from torchvision import transforms\n","#Code for making prediction\n","im_size = 112\n","mean=[0.485, 0.456, 0.406]\n","std=[0.229, 0.224, 0.225]\n","\n","train_transforms = transforms.Compose([\n","                                        transforms.ToPILImage(),\n","                                        transforms.Resize((im_size,im_size)),\n","                                        transforms.ToTensor(),\n","                                        transforms.Normalize(mean,std)])\n","\n","#keep the path to the video in the list below\n","path_to_videos = ['/content/drive/MyDrive/deep2.mp4']\n","\n","\n","video_dataset = validation_dataset(path_to_videos,sequence_length = 100,transform = train_transforms)\n","model = Model(2).cuda()\n","#paste the path to the model below\n","path_to_model = '/content/drive/MyDrive/model_87_acc_20_frames_final_data.pt'\n","model.load_state_dict(torch.load(path_to_model))\n","model.eval()\n","for i in range(0,len(path_to_videos)):\n","  print(path_to_videos[i])\n","  prediction = predict(model,video_dataset[i],'./')\n","  if prediction[0] == 1:\n","    print(\"REAL\")\n","  else:\n","    print(\"FAKE\")"]}],"metadata":{"accelerator":"GPU","colab":{"gpuType":"T4","provenance":[]},"kernelspec":{"display_name":"Python 3","name":"python3"}},"nbformat":4,"nbformat_minor":0}
